Ckpt1:
    script: curl -s https://courses.cs.washington.edu/courses/cse332/15au/homework/p3/gitlab-ci/ckpt1.sh | bash
Ckpt2:
    script: curl -s https://courses.cs.washington.edu/courses/cse332/15au/homework/p3/gitlab-ci/ckpt2.sh | bash
StaticAnalysis:
    script: curl -s https://courses.cs.washington.edu/courses/cse332/15au/homework/p3/gitlab-ci/static.sh | bash
